# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fb57184b853e6e74ede015d3052155d51af750ec9cdbd3739ed0af948aba905eff48af6bee9d6a438b129cece92107169615bfb4b3d409f9a6689bcef63ddf77

test:
  secret_key_base: 4cd17705c14e1b3a651b1dea1c6ca0a0aff9a711b59a46763b589dff67fe1da08b757effcdebcb1c112208f41344d4434de177aa406a15fa411c3716530a1022

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
